"use strict";
var scene = new THREE.Scene();
var aspect_ratio = window.innerWidth / window.innerHeight;
var camera = new THREE.PerspectiveCamera(75, aspect_ratio, 1, 10000);
camera.position.z = 500;
scene.add(camera);
var renderer = new THREE.WebGLRenderer({ alpha: true });
renderer.setSize(window.innerWidth, window.innerHeight);
document.body.appendChild(renderer.domElement);
var shape = new THREE.CubeGeometry(100, 100, 100);
var cover = new THREE.MeshNormalMaterial();
var box = new THREE.Mesh(shape, cover);
scene.add(box);
box.rotation.set(0.5, 0.5, 0.5);
var t = THREE;
var ball = new t.Mesh(new t.SphereGeometry(100, 20, 15), cover);
scene.add(ball);
ball.position.set(200, 0, 0);
var clock = new t.Clock();
var henger = new t.Mesh(new t.CylinderGeometry(20, 20, 100), cover);
henger.position.set(-200, 0, 0);
scene.add(henger);
animate();
renderer.render(scene, camera);
function animate() {
    requestAnimationFrame(animate);
    var time = clock.getElapsedTime();
    ball.rotation.set(time, time, 0);
    box.rotation.set(time, time, 0);
    henger.rotation.set(2 * time, 2 * time, 0);
    renderer.render(scene, camera);
}
